### ISSUE TITLE
请问可以更新一下教程吗

### ISSUE THREAD

**Issue by MineYuanlu** [AlbinZhu/yolov7-polygon-detection#2]
请问是否可以更新一下README，介绍一下基本用法？
我尝试使用但是遇到了错误，我不知道该怎么做

```
train: Scanning 'ifr\dataset\labels.cache' images and labels... 3 found, 0 missing, 0 empty, 3 corrupted: 100%|█████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
dict_values([])
Traceback (most recent call last):
  File "D:\yuanlu\dev\python\yolov7-polygon-detection\train_polygon.py", line 618, in <module>
    train(hyp, opt, device, tb_writer, polygon=opt.polygon)
  File "D:\yuanlu\dev\python\yolov7-polygon-detection\train_polygon.py", line 246, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "D:\yuanlu\dev\python\yolov7-polygon-detection\utils\datasets.py", line 72, in create_dataloader
    dataset = custom_dataset_class(path, imgsz, batch_size,
  File "D:\yuanlu\dev\python\yolov7-polygon-detection\utils\datasets.py", line 728, in __init__
    labels, shapes, self.segments = zip(*cache.values())
ValueError: not enough values to unpack (expected 3, got 0)
```

**Comment by AlbinZhu** [comment]
我更新了demo数据和训练脚本，希望能对你有所帮助，如果还有问题也欢迎提issue。
